export const ImageSources = {
  DOCTOR: require("./images/nurse-1.png"),
  APPOINTMENTS: require("./images/report.png"),
  MEDICINE_DISPENSE: require("./images/report-1.png"),
  EMERGENCY: require("./images/ambulance.png"),
  MEDICINE_SHOP: require("./images/pills.png"),
  CATCH_UP: require("./images/Layer_2_28_.png"),
  BANNER_1: require("./images/banner.png"),
  DOCTOR_PROFILE: require("./images/doctor-profile.png"),
  DOCTOR_APPOINTMENT: require("./images/doctor-appointment.png"),
  DOCTOR_MEDICINE_DISPENSE: require("./images/stethoscope.png"),
  DOCTOR_PRESCRIPTION: require("./images/drug.png"),
  DOCTOR_SKILL: require("./images/doctor-skill.png"),
  NURSE_NO_REFER: require("./images/emergency-kit.png"),
  VERY_SEVERE: require("./images/very-severe.png"),
  NO_PLAN: require("./images/no-plan.png"),
  MODERATE: require("./images/moderate.png"),
}
